spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
    prefix: classpath:/templates/
    
  activemq:
    broker-url: tcp://122.112.252.45:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
    
  mail:
    host: smtp.163.com
    username: shuye520com@163.com
    password: ABCabc123
    default-encoding: UTF-8
    properties: 
      mail-smtp-auth: true
      mail-smtp-starttls:
        enable: true
        required: true
    

logging:
  config: classpath:log4j2.xml
  

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude:
        - 
  
  
  